class <%= migration_class_name %> < ActiveRecord::Migration
  def change
    create_table :intel_searches do |t|
      t.string :search_type
      t.string :query
      t.string :normalized_query
      t.integer :results_count
      t.timestamp :created_at
      t.integer :convertable_id
      t.string :convertable_type
      t.timestamp :converted_at
    end

    add_index :intel_searches, [:created_at]
    add_index :intel_searches, [:search_type, :created_at]
    add_index :intel_searches, [:search_type, :normalized_query, :created_at], name: "index_intel_searches_on_search_type_and_normalized_query_and_cr" # autogenerated name is too long
    add_index :intel_searches, [:convertable_id, :convertable_type]
  end
end
